server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5MB

  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml

  datasource:
    url: jdbc:mysql://shoeshop.cwttoar5v1wj.us-east-2.rds.amazonaws.com:3306/shoeshop
    username: root
    password: adminnnn
    #url: jdbc:mysql://localhost:3306/shoeshop

  jpa:
    show-sql: true