server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5MB

  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml

  datasource:
    url: jdbc:mysql://localhost:3306/shoeshop
    username: root
    password: admin

  jpa:
    show-sql: true

jwt:
  secret: bXlzZWNyZXQ=
  validity: 86400000