server:
  port: 8080

spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml

  datasource:
    url: jdbc:mysql://localhost:3306/shoeshop
    username: root
    password: admin

  jpa:
    show-sql: true