server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5MB

  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml

  datasource:
    url: jdbc:mysql://shoeshop.cwttoar5v1wj.us-east-2.rds.amazonaws.com:3306/shoeshop
    username: root
    password: adminnnn
    #url: jdbc:mysql://localhost:3306/shoeshop

  mail:
    host: smtp.gmail.com
    port: 587
    username: shoeshop.notifications
    password: shoeshopmailing123
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jpa:
    show-sql: true

jwt:
  secret: bXlzZWNyZXQ=
  validity: 86400000